MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/matchers/DriveNavigationMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/matchers/RouteMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/screens/RouteView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/useractions/RouteActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/flow/RoutePlannerFlowTests.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/integration/RoutePlannerIntegrationTests.kt

Contains:
MSDKUI-883: [Android] Implementation - Integration tests for Route Planner/Route preview
MSDKUI-1457: [Android] [iOS] Check content of route description item on route maneuever list.
MSDKUI-883 Implemented as a new test case
MSDKUI-1457 Fixed RouteMatchers.checkRouteOverviewItemsDisplayed()

MSDKUI-883, MSDKUI-1457: Route preview test implementation

---

MSDKUIKit/MSDKUILib/src/main/res/values-zz-rZZ/strings.xml

Integrating Izumi strings for new translations.

MSDKUI-1232: [Android] Integrate the latest Izumi strings

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/utils/ManeuversActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/matchers/RouteMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/screens/RouteView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/useractions/RouteActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/flow/RoutePlannerFlowTests.kt

Test maneuvers list visibility

MSDKUI-545: Browse maneuvers list test implementation

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/integration/RoutePlannerIntegrationTests.kt

Show maneuvers list test implementation

MSDKUI-1472: Show maneuvers list test

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/annotation/CompatibilityUITest.java
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/annotation/FunctionalUITest.java
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/annotation/IntegrationUITest.java
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceEstimatedArrivalTimeViewFragment.kt
MSDKUIDemo/MSDKUIApp/src/main/res/drawable/rectangle_bg.xml
MSDKUIDemo/MSDKUIApp/src/main/res/values/attrs.xml
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/guidance/GuidanceEstimatedArrivalViewFragmentTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/testutils/MockUtils.kt
MSDKUIKit/MSDKUILib/src/main/res/drawable/ic_car_position_marker.xml
MSDKUIKit/MSDKUILib/src/main/res/layout/guidance_next_maneuver_panel.xml

Added missing copyright in files

MSDKUI-1671: Fix copyright headers as some files are missing it.

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/routepreview/RoutePreviewFragment.kt

accessibility focus moved to the last of ui once every ui component is ready

MSDKUI-1558: [Android] Accessibility - Guidance - Focus starts at the bottom of the screen

---

MSDKUIDemo/gradle.properties
MSDKUIKit/gradle.properties

Raised version number to 2.0.0 for demo app and lib

MSDKUI-1234: [Android] Raise version number

---

Documentation/Guides/QuickStart.md
Documentation/Guides/UserGuide.md
README.md

Plus a small update on the MSDKUIDarkTheme.

MSDKUI-1681: Raise version number for README

---

MSDKUIDemo/MSDKUIApp/build.gradle
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/core/CoreMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/flow/RoutePlannerFlowTests.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/routing/RoutePlannerPresenter.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/routing/RoutingIdlingResourceWrapper.kt
MSDKUIDemo/gradle.properties

RoutingIdlingResource added
withDateText matcher is changed to use DateFormatterUtil

MSDKUI-1673 testSetDepartureTime() fix

---

Documentation/Guides/QuickStart.md

Signed-off-by: Ogunreku Praise <35612274+jehovahmidara@users.noreply.github.com>

ESD-480: Fix Chapter Hierarchy for Quickstart Guide

---

Documentation/Guides_Examples/HelloMSDKUI/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/AndroidManifest.xml

Signed-off-by: Ogunreku Praise <35612274+jehovahmidara@users.noreply.github.com>

ESD-476: Limit Example Apps Orientation to Portrait mode

---

MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/RouteUtil.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/MockUtils.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/routing/RouteUtilTest.java

Route time to arrive include traffic at the same principle as traffic delay information.

MSDKUI-1694: RP No traffic delay is shown but considered in duration

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/guidance/useractions/GuidanceActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/guidance/integration/GuidanceIntegrationTests.kt

Signed-off-by: Marcin Lawicki <41331357+m1awicki@users.noreply.github.com>

MSDKUI-1281 Integration test for guidance next-next maneuver

---

MSDKUIKit/MSDKUILib/src/main/res/layout/maneuver_item.xml

Increased distance textview width.

MSDKUI-1692: RP & Guidance - Maneuver list distances alignment is off

---

MSDKUIKit/MSDKUILib/src/main/res/values/style.xml

MSDKUI-1700: Remove unnecessary "tools:targetApi" attributes

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/core/CoreActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/testdata/RoutingTestData.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/screens/RouteView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/screens/RoutePlannerView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/useractions/RoutePlannerActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/useractions/RoutePlannerBarActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/flow/RoutePlannerFlowTests.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/integration/RoutePlannerIntegrationTests.kt

Reorder waypoints test implementation
Cleanup

MSDKUI-549 Test reorder waypoints

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/core/CoreMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/matchers/DriveNavigationMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/guidance/screens/GuidanceView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/guidance/useractions/GuidanceActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/guidance/flow/GuidanceFlowTests.kt

Next-next maneuver panel test implementation

MSDKUI-1531 Implementation - Next-next maneuver panel

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/core/CoreMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/matchers/DriveNavigationMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/useractions/DriveNavigationActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/guidance/flow/GuidanceFlowTests.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/Constant.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/routepreview/RoutePreviewFragmentPresenter.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceActivity.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceCoordinator.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceRouteSelectionCoordinator.kt

Test implementation and simulation speed management

MSDKUI-1533 Test display current speed and speed limit warning

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/Provider.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/map/MapFragmentWrapper.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/map/MapFragmentWrapperTest.kt

Added unit tests for MapFragmentWrapper class.

MSDKUI-1697:[Android] Create unit tests for MapFragmentWrapper

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/Provider.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/map/MapFragmentWrapper.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/map/MapFragmentWrapperTest.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceManeuverView.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceManeuverViewSetting.kt
MSDKUIDev/app/src/main/res/layout/guidance_maneuver_view_fix_hori.xml
MSDKUIDev/app/src/main/res/layout/guidance_maneuver_view_fix_ver.xml
MSDKUIDev/app/src/main/res/layout/guidance_maneuver_view_hori.xml
MSDKUIDev/app/src/main/res/layout/guidance_maneuver_view_ver.xml

Modify the demo app to adopt behavior of 2 screen view

MSDKUI-1759: Implement the style handling

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/route/useractions/RouteActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/screens/RoutePlannerOptionsView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/useractions/RoutePlannerActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/useractions/RoutePlannerBarActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/useractions/RoutePlannerOptionsActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/flow/RoutePlannerFlowTests.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/integration/RoutePlannerIntegrationTests.kt

Additionally:
- Replaced standard waits with idling resource for route
calculations in route planner
- Reduced complexity of #testUpdateAWaypointAndVerifyRouteChanged
Signed-off-by: Ants Peetsalu <43877908+ants86@users.noreply.github.com>

MSDKUI-1646: Implement test for tunnel route option

---

Documentation/Guides/ContributionGuide.md

Signed-off-by: datasun@users.noreply.github.com <datasun@users.noreply.github.com>

ESD-496: Extend commit policy to include Dev app

---

CONTRIBUTING.md
Documentation/Guides/ContributionGuide.md
Documentation/Guides/QuickStart.md
Documentation/Guides/UserGuide.md

Signed-off-by: Ogunreku Praise <35612274+jehovahmidara@users.noreply.github.com>

ESD-485: Align chapter capitals and section headings

---

Documentation/Guides_Examples/HelloMSDKUI/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/java/com/here/msdkui/example/MainActivity.java
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/java/com/here/msdkui/example/MapInitializer.java
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/res/layout/activity_main.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/com/here/msdkui/example/GuidanceActivity.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/com/here/msdkui/example/MainActivity.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/com/here/msdkui/example/RouteDetailsActivity.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/GuidanceSimulator.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/MapInitializer.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/RouteCalculator.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/res/layout/activity_guidance.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/res/layout/activity_main.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/res/layout/activity_route_details.xml

Signed-off-by: Ogunreku Praise <35612274+jehovahmidara@users.noreply.github.com>

ESD-501: UIKit-Update all Source file Copyright HEADER from 2018 to 2019

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/routepreview/RoutePreviewFragmentPresenter.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceRouteSelectionActivity.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceRouteSelectionCoordinator.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/position/AppPositioningManager.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/guidance/GuidanceRouteSelectionActivityTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/position/AppPositioningManagerTest.kt

Rename current location to custom location and removed auto reset

MSDKUI-1775: [Android] Provide a way to inject custom location as a start location

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceNextManeuverFragment.kt
MSDKUIDemo/MSDKUIApp/src/main/res/layout/guidance_next_maneuver_fragment.xml
MSDKUIDemo/MSDKUIApp/src/main/res/values/dimens.xml
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/guidance/GuidanceNextManeuverViewFragmentTest.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceNextManeuverView.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceNextManeuverViewSetting.kt
MSDKUIDev/app/src/main/res/layout/guidance_next_maneuver_view.xml
MSDKUIDev/app/src/main/res/layout/guidance_next_maneuver_view_fix.xml
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceEstimatedArrivalView.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceManeuverView.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceNextManeuverData.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceNextManeuverPresenter.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceNextManeuverView.java
MSDKUIKit/MSDKUILib/src/main/res/layout/guidance_next_maneuver_panel.xml
MSDKUIKit/MSDKUILib/src/main/res/values/attrs.xml
MSDKUIKit/MSDKUILib/src/main/res/values/style.xml
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceEstimatedArrivalViewDataTest.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceNextManeuverDataTest.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceNextManeuverViewTest.java

Fixed GuidanceNextManeuverView -- Removed default option from dev app
GuidanceNextManeuverView -- added new option "without street name" in dev app
GuidanceNextManeuverView -- hide dot if street or distance view is gone
GuidanceNextManeuverView -- Fixed width

MSDKUI-1722: [Android] Component app findings

---

MSDKUIKit/MSDKUILib/src/main/res/layout/maneuver_item.xml

ManeuverItemView - Default - with all values, short instruction - remove outer spacing

MSDKUI-1722 [Android] Component app findings

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceSpeedFragment.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/ComponentList.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/Constant.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceEstimatedArrival.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceEstimatedArrivalSetting.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceManeuverView.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceManeuverViewSetting.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceNextManeuverViewSetting.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceSpeedLimit.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceStreetLabelSetting.kt
MSDKUIDev/app/src/main/res/layout/guidance_next_maneuver_view_fix.xml
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceSpeedView.java
MSDKUIKit/MSDKUILib/src/main/res/drawable-v21/current_street_name_bg.xml
MSDKUIKit/MSDKUILib/src/main/res/drawable/current_street_name_bg.xml
MSDKUIKit/MSDKUILib/src/main/res/layout/guidance_arrival_info.xml
MSDKUIKit/MSDKUILib/src/main/res/layout/guidance_current_speed_panel.xml
MSDKUIKit/MSDKUILib/src/main/res/layout/guidance_current_street.xml
MSDKUIKit/MSDKUILib/src/main/res/layout/guidance_maneuver_view_screen1.xml
MSDKUIKit/MSDKUILib/src/main/res/values/attrs.xml
MSDKUIKit/MSDKUILib/src/main/res/values/style.xml

Improved Guidance components UI, Added several options in DevApp for GuidanceManeuverview, GuidanceNextManeuverView, GuidanceEstimatedArrivalView etc

MSDKUI-1914: [Android] Improve guidance components layouts

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/core/CoreActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/core/CoreMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/core/CoreView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/testdata/Constants.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/utils/CurrentActivityUtils.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/matchers/DriveNavigationMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/useractions/DriveNavigationActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/guidance/screens/GuidanceView.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/guidance/useractions/GuidanceActions.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/routeplanner/matchers/RoutePlannerBarMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/guidance/flow/GuidanceFlowTests.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/guidance/integration/GuidanceIntegrationTests.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/routing/flow/RoutePlannerFlowTests.kt

Signed-off-by: Ants Peetsalu <43877908+ants86@users.noreply.github.com>

MSDKUI-1909: Make stability fixes for guidance tests

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/drivenavigation/matchers/DriveNavigationMatchers.kt
MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/tests/guidance/flow/GuidanceFlowTests.kt

Updated polling rates because test runs faster now.
Added mapView wait.
Signed-off-by: Ants Peetsalu <43877908+ants86@users.noreply.github.com>

Update ETA test

---

MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/ManeuverList.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/ManeuverListAdapter.java

Fixed the alignment by making it full width

MSDKUI-1900: [Android] Guidance/RP - Route overview maneuver list distances alignment off

---

MSDKUIDev/app/src/main/java/com/here/msdkuidev/ComponentList.kt
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceStreetLabelView.java

Improved street label corner handling
Sort DevApp component by names
Signed-off-by: Vijay Yadav <vijay.yadav@here.com>

MSDKUI-1914:[Android] Improve guidance components layouts

---

MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceSpeedView.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceSpeedViewSetting.kt
MSDKUIKit/MSDKUILib/src/main/res/values/style.xml

Signed-off-by: Vijay Yadav <vijay.yadav@here.com>

MSDKUI-1941: Android dev app - SpeedView - add options to test alignment

---

Documentation/Guides/ContributionGuide.md
Documentation/Guides/QuickStart.md
Documentation/Guides/UserGuide.md
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/HelloMSDKUI/build.gradle
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/com/here/msdkui/example/GuidanceActivity.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/res/layout/activity_guidance.xml
Documentation/Guides_Examples/MSDKUIPrimer/build.gradle
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/GuidanceManeuverView.java
README.md

- update required HERE SDK version
- update Android Gradle plugin to version 3.3.0 and Gradle to version 4.10.1
- update guides, apps and all other documents to MSDKUI 2.1.0
Signed-off-by: datasun <datasun@users.noreply.github.com>

MSDKUI-1844: Update examples and docs to MSDKUI version 2.1.0

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/map/MapFragmentWrapper.kt

MSDKUI-1966: Guidance App crashes with map tilted and taping on sky

---

MSDKUIKit/MSDKUILib/src/main/res/values/style.xml

MSDKUI-1811: Route result item icon alignment

---

MSDKUIKit/MSDKUILib/src/main/res/values/style.xml

MSDKUI-1811: [Android] Route result item icon alignment

---

MSDKUIKit/MSDKUILib/build.gradle
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceEstimatedArrivalViewPresenterTest.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceManeuverPresenterTest.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceNextManeuverPresenterTest.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceSpeedPresenterTest.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/GuidanceStreetLabelPresenterTest.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/guidance/base/BaseGuidancePresenterTest.java
MSDKUIKit/gradle.properties

MSDKUI-2108: Replace Powermock with Mockito where needed

---

Documentation/Guides/QuickStart.md
Documentation/Guides_Examples/HelloMSDKUI/app/build.gradle
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/java/com/here/msdkui/example/MainActivity.java
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/java/com/here/msdkui/example/MapInitializer.java
Documentation/Guides_Examples/HelloMSDKUI/build.gradle
Documentation/Guides_Examples/HelloMSDKUI/gradle.properties
Documentation/Guides_Examples/HelloMSDKUI/gradle/wrapper/gradle-wrapper.properties
Documentation/Guides_Examples/MSDKUIPrimer/app/build.gradle
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/com/here/msdkui/example/GuidanceActivity.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/com/here/msdkui/example/MainActivity.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/com/here/msdkui/example/RouteDetailsActivity.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/GuidanceSimulator.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/MapInitializer.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/RouteCalculator.java
Documentation/Guides_Examples/MSDKUIPrimer/build.gradle
Documentation/Guides_Examples/MSDKUIPrimer/gradle.properties
Documentation/Guides_Examples/MSDKUIPrimer/gradle/wrapper/gradle-wrapper.properties
README.md

Signed-off-by: datasun <datasun@users.noreply.github.com>

MSDKUI-2090: Migrate example apps to AndroidX

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/Provider.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/common/mapselection/WaypointSelectionPresenterTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/common/routepreview/RoutePreviewFragmentPresenterTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/guidance/GuidanceWaypointSelectionPresenterTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/testutils/MockUtils.kt
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/RouteBarScaler.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/RouteDescriptionHandler.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/RouteDescriptionList.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/RouteDescriptionListAdapter.java
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/RouteUtil.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/MockUtils.java
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/routing/RouteDescriptionsListTest.java

MSDKUI-2130: Update project dependencies

---

Documentation/Guides/ContributionGuide.md
Documentation/Guides/QuickStart.md
MSDKUIDemo/gradle.properties
MSDKUIDev/app/build.gradle
MSDKUIKit/gradle.properties
README.md

MSDKUI-2132: Update version number

---

.travis.yml
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/guidance/base/BaseGuidancePresenter.java
MSDKUIKit/coverage.gradle
MSDKUIKit/gradle.properties

Handled NavigationManager.RerouteListener class changes in SDK 3.14

MSDKUI-2197: Handle deprecations & breaking changes

---

MSDKUIDemo/MSDKUIApp/src/androidTest/java/com/here/msdkuiapp/espresso/impl/views/map/useractions/MapActions.kt
MSDKUIDemo/MSDKUIApp/src/main/AndroidManifest.xml
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/base/BaseActivity.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/common/routepreview/RoutePreviewFragmentPresenter.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceCoordinator.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceRouteSelectionCoordinator.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/landing/LandingActivity.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/map/MapFragmentWrapper.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/routing/RoutePlannerPresenter.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/guidance/GuidanceRouteSelectionCoordinatorTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/landing/LandingActivityTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/routing/RoutePlannerPresenterTest.kt

MSDKUI-2247: Handle deprecations & breaking changes

---

MSDKUIDemo/build.gradle
MSDKUIDemo/gradle.properties
MSDKUIDev/build.gradle
MSDKUIKit/build.gradle
MSDKUIKit/gradle.properties

MSDKUI-2234: Update project dependencies

---

Documentation/Guides/ContributionGuide.md
Documentation/Guides/QuickStart.md
MSDKUIDemo/gradle.properties
MSDKUIDev/app/build.gradle
MSDKUIKit/gradle.properties
README.md

MSDKUI-2236: Update version number

---

Documentation/Guides_Examples/HelloMSDKUI/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/java/com/here/msdkui/example/MapInitializer.java
Documentation/Guides_Examples/HelloMSDKUI/build.gradle
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/MapInitializer.java
Documentation/Guides_Examples/MSDKUIPrimer/build.gradle

MSDKUI-2241: Update examples

---

Documentation/Guides/QuickStart.md

MSDKUI-2243: Update documentation

---

CONTRIBUTING.md
Documentation/Guides/ContributionGuide.md
Documentation/Guides/QuickStart.md
Documentation/Guides/UserGuide.md
Documentation/Guides_Examples/HelloMSDKUI/README.md
Documentation/Guides_Examples/MSDKUIPrimer/README.md
MSDKUIDemo/README.md
README.md

Signed-off-by: ogunreku praise <35612274+jehovahmidara@users.noreply.github.com>

ESD-810: Update Product Names

---

MSDKUIDemo/MSDKUIApp/src/main/AndroidManifest.xml
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/base/BaseActivity.kt

Removed map service definition because it is now present in SDK
manifest. Updated deprecated function.

MSDKUI-2292: Handle deprecations & breaking changes

---

Documentation/Guides_Examples/HelloMSDKUI/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/java/com/here/msdkui/example/MapInitializer.java
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/java/helper/MapInitializer.java

Removed map service definition because it is now present in SDK
manifest. Updated deprecated function.

MSDKUI-2300: Update examples

---

Documentation/Guides/QuickStart.md

Removed map service definition because it is now present in SDK
manifest.

MSDKUI-2288: Update documentation

---

Documentation/Guides/ContributionGuide.md
Documentation/Guides/QuickStart.md
MSDKUIDemo/gradle.properties
MSDKUIDev/app/build.gradle
MSDKUIKit/gradle.properties
README.md

MSDKUI-2286: Update version number

---

MSDKUIDemo/gradle.properties
MSDKUIKit/gradle.properties

MSDKUI-2337: Update project dependencies

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceActivity.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/guidance/GuidanceCoordinator.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/routing/RoutePlannerFragment.kt
MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/routing/RoutingCoordinator.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/guidance/GuidanceActivityTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/routing/RoutePlannerFragmentTest.kt
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/routing/RoutingCoordinatorTest.kt

MSDKUI-2308: Fix assemble warnings

---

MSDKUIDemo/MSDKUIApp/src/main/java/com/here/msdkuiapp/base/BaseActivity.kt

Scooter routing is not working because of old map data. Now app will try
to migrate data at old path into new one, after this operation old data
will be removed and app will use only data at new path (either
successfully migrated data or completely new downloaded data).

MSDKUI-2162: Demo app - Scooter routing doesn't work

---

.travis.yml
MSDKUIDemo/MSDKUIApp/src/main/res/layout-land/guidance_dashboard.xml
MSDKUIDemo/MSDKUIApp/src/main/res/layout/guidance_dashboard.xml
MSDKUIDemo/MSDKUIApp/src/main/res/layout/guidance_waypoint_selection.xml
MSDKUIDemo/MSDKUIApp/src/main/res/layout/home_actionbar.xml
MSDKUIDemo/MSDKUIApp/src/main/res/layout/waypoint_selection.xml
MSDKUIDemo/MSDKUIApp/src/test/java/com/here/msdkuiapp/routing/RoutePlannerPresenterTest.kt
MSDKUIDemo/build.gradle
MSDKUIDemo/gradle.properties
MSDKUIDemo/gradle/wrapper/gradle-wrapper.properties
MSDKUIDev/app/build.gradle
MSDKUIDev/app/src/main/java/com/here/msdkuidev/ComponentList.kt
MSDKUIDev/build.gradle
MSDKUIDev/gradle/wrapper/gradle-wrapper.properties
MSDKUIKit/MSDKUILib/build.gradle
MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/routing/BooleanOptionItem.java
MSDKUIKit/MSDKUILib/src/main/res/layout/boolean_option_item.xml
MSDKUIKit/MSDKUILib/src/test/java/com/here/msdkui/routing/BooleanOptionItemTest.java
MSDKUIKit/build.gradle
MSDKUIKit/gradle.properties
MSDKUIKit/gradle/wrapper/gradle-wrapper.properties
MSDKUIKit/quality.gradle
MSDKUIKit/quality/spotbugs/spotbugs-filter.xml

Increased also version of: target android sdk, kotlin, mockito,
spotbugs. Spotbugs task has been removed because now its automatically
part of 'check' task.

MSDKUI-2309: Update Android Gradle Plugin

---

Documentation/Guides/QuickStart.md
README.md

MSDKUI-2341: Update documentation

---

MSDKUIDemo/MSDKUIApp/src/main/AndroidManifest.xml
MSDKUIDemo/build.gradle
MSDKUIDemo/gradle.properties
MSDKUIDev/app/build.gradle
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceEstimatedArrival.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceManeuverView.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceNextManeuverView.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceSpeedLimit.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceSpeedView.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/GuidanceStreetLabel.kt
MSDKUIDev/app/src/main/java/com/here/msdkuidev/component/ManeuverItemView.kt
MSDKUIDev/build.gradle
MSDKUIKit/MSDKUILib/src/main/res/layout/numeric_option_item_edittext.xml
MSDKUIKit/build.gradle
MSDKUIKit/gradle.properties

MSDKUI-2383: Update project dependencies

---

Documentation/Guides/QuickStart.md
Documentation/Guides_Examples/HelloMSDKUI/app/build.gradle
Documentation/Guides_Examples/HelloMSDKUI/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/HelloMSDKUI/build.gradle
Documentation/Guides_Examples/MSDKUIPrimer/app/build.gradle
Documentation/Guides_Examples/MSDKUIPrimer/app/src/main/AndroidManifest.xml
Documentation/Guides_Examples/MSDKUIPrimer/build.gradle
README.md

MSDKUI-2387: Update documentation

---

MSDKUIDemo/MSDKUIApp/build.gradle
MSDKUIDev/app/build.gradle

MSDKUI-2452: Fix quick start guide

---

Documentation/Guides/ContributionGuide.md
Documentation/Guides/QuickStart.md
MSDKUIDemo/gradle.properties
MSDKUIDev/app/build.gradle
MSDKUIKit/gradle.properties
README.md

MSDKUI-2474: Update version number
